# Generated by Django 3.1.7 on 2021-05-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadModel',
        ),
    ]
